name: Create Lamba Function
on:
  workflow_dispatch:
    inputs:
      functionName:
        type: string
        description: "Name of Lambda Function"
        required: true
        default: "Enter Function Name"
env:
  functionName: LambdaFunctionOverHttps
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-southeast-2
jobs:
  updateLambda:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    environment: language-app
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: test secrets
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Creating Python File
        run: |
          python3 ./lambda-functions/createLambda.py -f ${{ inputs.functionName }}
      - name: Commit Files
        run: |
          git config --global user.email "harrison.falconer2@gmail.com"
          git config --global user.name "Harry Kim"
          git add .
          git commit -m "Automatic commit from createLambda workflow"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Zip function"
        run: |
          zip code.zip lambda-functions/${{ inputs.functionName }}.py 
      - name: "Creating Lambda Function"
        run: aws lambda create-function --function-name ${{ inputs.functionName }} --zip-file fileb://code.zip --handler ${{ inputs.functionName }}.lambda_handler --runtime python3.12 --role arn:aws:iam::767398145545:role/lambda-apigateway-role