name: Lambda update workflow for LambdaFunctionOverHttps
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      -  lambda-functions/LambdaFunctionOverHttps.py
env:
  functionName: LambdaFunctionOverHttps
  
jobs:
  updateLambda:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: "Zip function"
        run: |
          zip code.zip lambda-functions/${{ env.functionName }}.py 
      - name: "Updated lambda"
        run: aws lambda update-function-code --function-name ${{ env.functionName }} --zip-file fileb://code.zip
