name: Lambda update workflow for LambdaFunctionOverHttps
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      -  lambda-functions/LambdaFunctionOverHttps.py
env:
  functionName: LambdaFunctionOverHttps
  
jobs:
  updateLambda:
    runs-on: ubuntu-latest
    steps:
      - name: "Updated function on push"
        run: |
          ./lambda-functions/${{ env.functionName }}.py
        # zip code.zip ./lambda-functions/${{ env.functionName }}.py
        # aws lambda update-function-code \                                                 
        # --function-name ${{ env.functionName }} \              
        # --zip-file code.zip
